### ISSUE TITLE
Issues with unwanted forced selection

### ISSUE THREAD

**Issue by paulyoung** [mjrussell/draft-js-autocomplete-plugin-creator#9]
I'm still debugging this, but I can consistently reproduce an issue where when I expect the list of suggestions to appear, the editor state is updated with `forceSelection: true` and the anchor and focus offsets are set to 0.

For example: 
* There's a list of suggestions containing `foo.bar` and `baz.qux`.
* I type `foo` or `baz` and everything is fine.
* As soon as I type `.` (resulting in `foo.` or `baz.`) the bug is triggered.

**Comment by paulyoung** [comment]
FWIW, I set `plugins` to an empty array (`[]`) and the issue went away.

**Comment by paulyoung** [comment]
I've also just seen this when I made a typo and hit backspace.

**Comment by paulyoung** [comment]
For some reason, under certain circumstances [`documentSelection.needsRecovery` is `true`](https://github.com/facebook/draft-js/blob/301d12ced979d03e12acc9a1474e54d89509691d/src/component/handlers/edit/editOnSelect.js#L38) and `updatedSelectionState` has `anchorOffset: 0` and `focusOffset: 0`.

<img width="808" alt="screen shot 2017-01-09 at 5 15 28 pm" src="https://cloud.githubusercontent.com/assets/84700/21775759/4209cdc0-d68f-11e6-9fab-6674ec56ba8c.png">

**Comment by paulyoung** [comment]
Up until I type `.` [`anchorIsTextNode` and `focusIsTextNode`](https://github.com/facebook/draft-js/blob/301d12ced979d03e12acc9a1474e54d89509691d/src/component/selection/getDraftEditorSelectionWithNodes.js#L48) are both `true`.

When I type `.` they are both `false`.

**Comment by paulyoung** [comment]
This sounds similar: https://github.com/facebook/draft-js/issues/400

**Comment by paulyoung** [comment]
I can consistently reproduce these 3 issues:

1. Type `foo.`. See the cursor move to the beginning. The editor reads `foo.`.
2. Type `foo`. Hit backspace. See the cursor move to the beginning. The editor reads `fo`.
3. Hit ⌘ + ←. See the cursor move to the beginning. Type `f`. See the cursor move to the beginning. Type `oo`. The editor reads `oof`.

**Comment by paulyoung** [comment]
Doing the following addresses the first, but it seems like there's some underlying issue that could be fixed somewhere more central.

```diff
diff --git a/src/CompletionSuggestionsPortal/index.js b/src/CompletionSuggestionsPortal/index.js
index 687777c..97893db 100644
--- a/src/CompletionSuggestionsPortal/index.js
+++ b/src/CompletionSuggestionsPortal/index.js
@@ -1,4 +1,5 @@
 import React, { Component } from 'react';
+import { EditorState } from 'draft-js';

 export default class CompletionSuggestionsPortal extends Component {

@@ -7,7 +8,13 @@ export default class CompletionSuggestionsPortal extends Component {
     this.updatePortalClientRect(this.props);

     // trigger a re-render so the MentionSuggestions becomes active
-    this.props.setEditorState(this.props.getEditorState());
+    const editorState = this.props.getEditorState();
+    const selectionState = editorState.getSelection();
+
+    this.props.setEditorState(
+      EditorState.forceSelection(editorState, selectionState)
+    );
   }
```

**Comment by paulyoung** [comment]
To clarify on the second issue – what I described about is when there is already some initial content.

I can also reproduce the issue with no initial content (`editorState` is the result of `EditorState.createEmpty()`).

That's to say that the cursor moves to the beginning after a character is typed _if the cursor was already at the beginning before the character was typed_.

**Comment by paulyoung** [comment]
Locally, I modified the issues example and could only reproduce after upgrading to `draft-js-plugins-editor@2.0.0-beta9`.

I tried all of the published beta version and they all produce the issue.

**Comment by paulyoung** [comment]
I pushed a branch called [`bug-demo`](https://github.com/paulyoung/draft-js-autocomplete-plugin-creator/tree/bug-demo) which reproduces the issues.

Below are some gifs which demonstrate what I've described above.

***

_Selection is forced to the beginning when the strategy regex matches_

![bug1](https://cloud.githubusercontent.com/assets/84700/21805966/ec9c10dc-d72e-11e6-85ae-b54740e0980f.gif)

***

_Backspace causes the selection to be forced to the beginning_

![bug2](https://cloud.githubusercontent.com/assets/84700/21805973/fa60d644-d72e-11e6-8bc4-b78564cdd760.gif)

***

_When the cursor is at the beginning, the selection is forced to the beginning after a character is typed_

![bug3](https://cloud.githubusercontent.com/assets/84700/21806009/1f595764-d72f-11e6-99e2-36520faa1692.gif)

**Comment by mjrussell** [comment]
@paulyoung so then we should way on merging #8 right because this works properly with plugins v1? I have seen similar issues when either the draft-js css was incorrect (possibly needs to be replaced) or it was inputing invalid blocks into the dom or ones that did not have data keys attached

**Comment by paulyoung** [comment]
I'm going to close this since it seems that all of the issues described are down to `draft-js-plugins-editor`. I'll open an issue there.

In fact, I'm currently using something roughly equivalent to the `PluginEditor` (`2.0.0-beta9`) they export except it only includes the subset of features I need to make `draft-js-autocomplete-plugin-creator` work.

I might be able to pinpoint the cause of these issues that way but might need to just go with my custom version if I run out of time.

Regarding #8 and v1 compatibility, I think that has already been broken by #4.

**Comment by paulyoung** [comment]
I figured out a workaround: https://github.com/draft-js-plugins/draft-js-plugins/issues/637#issuecomment-271922312

That was really annoying and difficult to track down.

**Comment by mjrussell** [comment]
Yeah I was thinking of reverting it, and doing a new release. Unfortunately finding time to work on this during the week is difficult, will spend some time on it this weekend

**Comment by paulyoung** [comment]
Thanks for the heads up. I'll probably need to point to my fork in the meantime.

**Comment by mjrussell** [comment]
@paulyoung I merged all the PRs and did a couple of minor edits and pushed it as `2.0.0-beta`. Its under the `beta2` tag so it wont be installed by default with npm install. It looked great in the issue example. Let me know if it looks good to you. Thanks for all your help with this
